/* Тодо Бичик — service worker (офлайн-кэш). */
const CACHE = 'todo-bichig-v48';

const PRECACHE = [
  './',
  './index.html',
  './writer.html',
  './manifest.webmanifest',
  './css/fonts.css',
  './css/style.css',
  './fonts/ibm-plex-sans/faces.css',
  './fonts/ibm-plex-sans/cyrillic-400-normal.woff2',
  './fonts/ibm-plex-sans/cyrillic-500-normal.woff2',
  './fonts/ibm-plex-sans/cyrillic-600-normal.woff2',
  './fonts/ibm-plex-sans/cyrillic-700-normal.woff2',
  './fonts/ibm-plex-sans/cyrillic-ext-400-normal.woff2',
  './fonts/ibm-plex-sans/cyrillic-ext-500-normal.woff2',
  './fonts/ibm-plex-sans/cyrillic-ext-600-normal.woff2',
  './fonts/ibm-plex-sans/cyrillic-ext-700-normal.woff2',
  './fonts/ibm-plex-sans/latin-400-normal.woff2',
  './fonts/ibm-plex-sans/latin-500-normal.woff2',
  './fonts/ibm-plex-sans/latin-600-normal.woff2',
  './fonts/ibm-plex-sans/latin-700-normal.woff2',
  './fonts/ibm-plex-sans/latin-ext-400-normal.woff2',
  './fonts/ibm-plex-sans/latin-ext-500-normal.woff2',
  './fonts/ibm-plex-sans/latin-ext-600-normal.woff2',
  './fonts/ibm-plex-sans/latin-ext-700-normal.woff2',
  './js/font-data.js',
  './js/barintodo-data.js',
  './js/data.js',
  './js/harmony-data.js',
  './js/reading-data.js',
  './js/utils.js',
  './js/audio.js',
  './js/lessons.js',
  './audio/vowels/a.mp3',
  './audio/vowels/e.mp3',
  './audio/vowels/i.mp3',
  './audio/vowels/o.mp3',
  './audio/vowels/u.mp3',
  './audio/vowels/oe.mp3',
  './audio/vowels/ue.mp3',
  './audio/long_vowels/aa.mp3',
  './audio/long_vowels/ee.mp3',
  './audio/long_vowels/ii.mp3',
  './audio/long_vowels/oo.mp3',
  './audio/long_vowels/uu.mp3',
  './audio/long_vowels/oee.mp3',
  './audio/long_vowels/oeu.mp3',
  './audio/diphthongs/ayi.mp3',
  './audio/diphthongs/eyi.mp3',
  './audio/diphthongs/iyi.mp3',
  './audio/diphthongs/oyi.mp3',
  './audio/diphthongs/uyi.mp3',
  './audio/diphthongs/oeyi.mp3',
  './audio/diphthongs/ueyi.mp3',
  './audio/consonants/n.mp3',
  './audio/consonants/ng.mp3',
  './audio/consonants/x.mp3',
  './audio/consonants/gh.mp3',
  './audio/consonants/b1.mp3',
  './audio/consonants/b2.mp3',
  './audio/consonants/s.mp3',
  './audio/consonants/sh.mp3',
  './audio/consonants/t.mp3',
  './audio/consonants/d.mp3',
  './audio/consonants/l.mp3',
  './audio/consonants/m.mp3',
  './audio/consonants/c.mp3',
  './audio/consonants/z.mp3',
  './audio/consonants/y.mp3',
  './audio/consonants/k1.mp3',
  './audio/consonants/k1n.mp3',
  './audio/consonants/k2.mp3',
  './audio/consonants/k2n.mp3',
  './audio/consonants/g1.mp3',
  './audio/consonants/g1n.mp3',
  './audio/consonants/q.mp3',
  './audio/consonants/r.mp3',
  './audio/consonants/v.mp3',
  './audio/galik/pb1.mp3',
  './audio/galik/pb2.mp3',
  './audio/galik/pf1.mp3',
  './audio/galik/pf2.mp3',
  './audio/galik/ch.mp3',
  './audio/galik/z1.mp3',
  './audio/galik/z2.mp3',
  './audio/galik/z3.mp3',
  './audio/galik/j.mp3',
  './audio/galik/xh.mp3',
  './audio/elements/nurhun.mp3',
  './audio/elements/udan.mp3',
  './audio/elements/titm.mp3',
  './audio/elements/aran.mp3',
  './audio/elements/neg_ceq.mp3',
  './audio/elements/xoyor_ceq.mp3',
  './audio/elements/togrg_ceq.mp3',
  './audio/elements/uru_tatasn.mp3',
  './audio/elements/kuchlg.mp3',
  './audio/numbers/0.mp3',
  './audio/numbers/1.mp3',
  './audio/numbers/2.mp3',
  './audio/numbers/3.mp3',
  './audio/numbers/4.mp3',
  './audio/numbers/5.mp3',
  './audio/numbers/6.mp3',
  './audio/numbers/7.mp3',
  './audio/numbers/8.mp3',
  './audio/numbers/9.mp3',
  './audio/punctuation/birga.mp3',
  './audio/punctuation/point4.mp3',
  './audio/punctuation/comma.mp3',
  './audio/punctuation/colon.mp3',
  './audio/words/w01.mp3',
  './audio/words/w02.mp3',
  './audio/words/w03.mp3',
  './audio/words/w04.mp3',
  './audio/words/w05.mp3',
  './audio/words/w06.mp3',
  './audio/words/w07.mp3',
  './audio/words/w08.mp3',
  './audio/words/w09.mp3',
  './audio/words/w10.mp3',
  './audio/words/w11.mp3',
  './audio/words/w12.mp3',
  './audio/words/w13.mp3',
  './audio/words/w14.mp3',
  './audio/words/w15.mp3',
  './audio/words/w16.mp3',
  './audio/words/w17.mp3',
  './audio/words/w18.mp3',
  './audio/words/w19.mp3',
  './audio/words/w20.mp3',
  './audio/words/w21.mp3',
  './audio/words/w22.mp3',
  './audio/words/w23.mp3',
  './audio/words/w24.mp3',
  './audio/words/w25.mp3',
  './audio/words/w26.mp3',
  './audio/words/w27.mp3',
  './audio/words/w28.mp3',
  './audio/words/w29.mp3',
  './audio/reading/expr/e01.mp3',
  './audio/reading/expr/e02.mp3',
  './audio/reading/expr/e03.mp3',
  './audio/reading/expr/e04.mp3',
  './audio/reading/expr/e05.mp3',
  './audio/reading/expr/e06.mp3',
  './audio/reading/expr/e07.mp3',
  './audio/reading/expr/e08.mp3',
  './audio/reading/expr/e09.mp3',
  './audio/reading/expr/e10.mp3',
  './audio/reading/expr/e11.mp3',
  './audio/reading/expr/e12.mp3',
  './audio/reading/expr/e13.mp3',
  './audio/reading/expr/e14.mp3',
  './audio/reading/expr/e15.mp3',
  './audio/reading/expr/e16.mp3',
  './audio/reading/expr/e17.mp3',
  './audio/reading/expr/e18.mp3',
  './audio/reading/expr/e19.mp3',
  './audio/reading/expr/e20.mp3',
  './audio/reading/expr/e21.mp3',
  './audio/reading/expr/e22.mp3',
  './audio/reading/riddles/r01q.mp3',
  './audio/reading/riddles/r01a.mp3',
  './audio/reading/riddles/r02q.mp3',
  './audio/reading/riddles/r02a.mp3',
  './audio/reading/riddles/r03q.mp3',
  './audio/reading/riddles/r03a.mp3',
  './audio/reading/riddles/r04q.mp3',
  './audio/reading/riddles/r04a.mp3',
  './audio/reading/riddles/r05q.mp3',
  './audio/reading/riddles/r05a.mp3',
  './audio/reading/riddles/r06q.mp3',
  './audio/reading/riddles/r06a.mp3',
  './audio/reading/riddles/r07q.mp3',
  './audio/reading/riddles/r07a.mp3',
  './audio/reading/riddles/r08q.mp3',
  './audio/reading/riddles/r08a.mp3',
  './audio/reading/riddles/r09q.mp3',
  './audio/reading/riddles/r09a.mp3',
  './audio/compose/c01.mp3',
  './audio/compose/c02.mp3',
  './audio/compose/c03.mp3',
  './audio/compose/c04.mp3',
  './audio/compose/c05.mp3',
  './audio/compose/c06.mp3',
  './audio/compose/c07.mp3',
  './audio/compose/c08.mp3',
  './audio/compose/c09.mp3',
  './audio/compose/c10.mp3',
  './audio/compose/c11.mp3',
  './audio/compose/c12.mp3',
  './audio/compose/c13.mp3',
  './audio/compose/c14.mp3',
  './audio/compose/c15.mp3',
  './audio/compose/c16.mp3',
  './audio/compose/c17.mp3',
  './audio/compose/c18.mp3',
  './audio/compose/c19.mp3',
  './audio/compose/c20.mp3',
  './audio/compose/c21.mp3',
  './audio/compose/c22.mp3',
  './audio/compose/c23.mp3',
  './audio/compose/c24.mp3',
  './audio/compose/c25.mp3',
  './audio/compose/c26.mp3',
  './audio/compose/c27.mp3',
  './audio/compose/c28.mp3',
  './audio/compose/c29.mp3',
  './audio/compose/c30.mp3',
  './audio/compose/c31.mp3',
  './audio/compose/c32.mp3',
  './audio/compose/c33.mp3',
  './audio/compose/c34.mp3',
  './audio/compose/c35.mp3',
  './audio/compose/c36.mp3',
  './audio/compose/c37.mp3',
  './audio/compose/c38.mp3',
  './audio/compose/c39.mp3',
  './audio/compose/c40.mp3',
  './audio/compose/c41.mp3',
  './audio/compose/c42.mp3',
  './audio/compose/c43.mp3',
  './audio/compose/c44.mp3',
  './audio/compose/c45.mp3',
  './audio/compose/c46.mp3',
  './audio/compose/c47.mp3',
  './audio/compose/c48.mp3',
  './audio/compose/c49.mp3',
  './audio/compose/c50.mp3',
  './audio/compose/c51.mp3',
  './audio/compose/c52.mp3',
  './audio/compose/c53.mp3',
  './audio/compose/c54.mp3',
  './audio/syllables/na.mp3',
  './audio/syllables/ne.mp3',
  './audio/syllables/ni.mp3',
  './audio/syllables/no.mp3',
  './audio/syllables/nu.mp3',
  './audio/syllables/noe.mp3',
  './audio/syllables/nue.mp3',
  './audio/syllables/ang.mp3',
  './audio/syllables/eng.mp3',
  './audio/syllables/ing.mp3',
  './audio/syllables/ong.mp3',
  './audio/syllables/ung.mp3',
  './audio/syllables/oeng.mp3',
  './audio/syllables/ueng.mp3',
  './audio/syllables/noeng.mp3',
  './audio/syllables/nueng.mp3',
  './audio/syllables/xa.mp3',
  './audio/syllables/xo.mp3',
  './audio/syllables/xu.mp3',
  './audio/syllables/gha.mp3',
  './audio/syllables/gho.mp3',
  './audio/syllables/ghu.mp3',
  './audio/syllables/ba.mp3',
  './audio/syllables/be.mp3',
  './audio/syllables/bi.mp3',
  './audio/syllables/bo.mp3',
  './audio/syllables/bu.mp3',
  './audio/syllables/boe.mp3',
  './audio/syllables/bue.mp3',
  './audio/syllables/pa.mp3',
  './audio/syllables/pe.mp3',
  './audio/syllables/pi.mp3',
  './audio/syllables/po.mp3',
  './audio/syllables/pu.mp3',
  './audio/syllables/poe.mp3',
  './audio/syllables/pue.mp3',
  './audio/syllables/fa.mp3',
  './audio/syllables/fe.mp3',
  './audio/syllables/fi.mp3',
  './audio/syllables/fo.mp3',
  './audio/syllables/fu.mp3',
  './audio/syllables/foe.mp3',
  './audio/syllables/fue.mp3',
  './audio/syllables/sa.mp3',
  './audio/syllables/se.mp3',
  './audio/syllables/si.mp3',
  './audio/syllables/so.mp3',
  './audio/syllables/su.mp3',
  './audio/syllables/soe.mp3',
  './audio/syllables/sue.mp3',
  './audio/syllables/sha.mp3',
  './audio/syllables/she.mp3',
  './audio/syllables/shi.mp3',
  './audio/syllables/sho.mp3',
  './audio/syllables/shu.mp3',
  './audio/syllables/shoe.mp3',
  './audio/syllables/shue.mp3',
  './audio/syllables/ta.mp3',
  './audio/syllables/te.mp3',
  './audio/syllables/ti.mp3',
  './audio/syllables/to.mp3',
  './audio/syllables/tu.mp3',
  './audio/syllables/toe.mp3',
  './audio/syllables/tue.mp3',
  './audio/syllables/da.mp3',
  './audio/syllables/de.mp3',
  './audio/syllables/di.mp3',
  './audio/syllables/do.mp3',
  './audio/syllables/du.mp3',
  './audio/syllables/doe.mp3',
  './audio/syllables/due.mp3',
  './audio/syllables/la.mp3',
  './audio/syllables/le.mp3',
  './audio/syllables/li.mp3',
  './audio/syllables/lo.mp3',
  './audio/syllables/lu.mp3',
  './audio/syllables/loe.mp3',
  './audio/syllables/lue.mp3',
  './audio/syllables/ma.mp3',
  './audio/syllables/me.mp3',
  './audio/syllables/mi.mp3',
  './audio/syllables/mo.mp3',
  './audio/syllables/mu.mp3',
  './audio/syllables/moe.mp3',
  './audio/syllables/mue.mp3',
  './audio/syllables/ca.mp3',
  './audio/syllables/ce.mp3',
  './audio/syllables/chi.mp3',
  './audio/syllables/co.mp3',
  './audio/syllables/cu.mp3',
  './audio/syllables/coe.mp3',
  './audio/syllables/cue.mp3',
  './audio/syllables/za.mp3',
  './audio/syllables/ze.mp3',
  './audio/syllables/zi.mp3',
  './audio/syllables/zo.mp3',
  './audio/syllables/zu.mp3',
  './audio/syllables/zoe.mp3',
  './audio/syllables/zue.mp3',
  './audio/syllables/ja.mp3',
  './audio/syllables/je.mp3',
  './audio/syllables/ji.mp3',
  './audio/syllables/jo.mp3',
  './audio/syllables/ju.mp3',
  './audio/syllables/joe.mp3',
  './audio/syllables/jue.mp3',
  './audio/syllables/ya.mp3',
  './audio/syllables/ye.mp3',
  './audio/syllables/yi.mp3',
  './audio/syllables/yo.mp3',
  './audio/syllables/yu.mp3',
  './audio/syllables/yoe.mp3',
  './audio/syllables/yue.mp3',
  './audio/syllables/ka.mp3',
  './audio/syllables/ko.mp3',
  './audio/syllables/ku.mp3',
  './audio/syllables/ke.mp3',
  './audio/syllables/ki.mp3',
  './audio/syllables/koe.mp3',
  './audio/syllables/kue.mp3',
  './audio/syllables/ge.mp3',
  './audio/syllables/gi.mp3',
  './audio/syllables/goe.mp3',
  './audio/syllables/gue.mp3',
  './audio/syllables/ra.mp3',
  './audio/syllables/re.mp3',
  './audio/syllables/ri.mp3',
  './audio/syllables/ro.mp3',
  './audio/syllables/ru.mp3',
  './audio/syllables/roe.mp3',
  './audio/syllables/rue.mp3',
  './audio/syllables/va.mp3',
  './audio/syllables/ve.mp3',
  './audio/syllables/vi.mp3',
  './audio/syllables/vo.mp3',
  './audio/syllables/vu.mp3',
  './audio/syllables/voe.mp3',
  './audio/syllables/vue.mp3',
  './audio/syllables/ha.mp3',
  './audio/syllables/he.mp3',
  './audio/syllables/hi.mp3',
  './audio/syllables/ho.mp3',
  './audio/syllables/hu.mp3',
  './audio/syllables/hoe.mp3',
  './audio/syllables/hue.mp3',
  './js/ui.js',
  './js/search.js',
  './js/practice.js',
  './js/harmony.js',
  './js/path.js',
  './js/copybook.js',
  './js/writer.js',
  './js/main.js',
  './js/writer-data.js',
  './js/writer-strokes-saved.js',
  './js/vendor/jspdf.umd.min.js',
  './img/icons/logo-192.png',
  './img/icons/icon-192.png',
  './img/icons/icon-512.png',
  './img/icons/icon-512-maskable.png',
  './img/icons/apple-touch-icon.png',
  './img/zaya-pandita.webp',
  './img/zaya-pandita.jpg',
  './img/badmaev.jpg',
  './img/vowels-strokes.webp',
  './img/vowels-strokes.jpg',
  './img/consonants-strokes-1.webp',
  './img/consonants-strokes-1.jpg',
  './img/consonants-strokes-2.webp',
  './img/consonants-strokes-2.jpg',
  './img/copybook/1.webp',
  './img/copybook/2.webp',
  './img/copybook/3.webp'
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) =>
      cache.addAll(PRECACHE).catch((err) => {
        console.warn('[sw] precache partial fail', err);
        return Promise.all(
          PRECACHE.map((url) =>
            cache.add(url).catch((e) => console.warn('[sw] skip', url, e))
          )
        );
      })
    ).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // HTML: сеть в приоритете, офлайн — из кэша
  if (req.mode === 'navigate' || (req.headers.get('accept') || '').includes('text/html')) {
    event.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
          return res;
        })
        .catch(() =>
          caches.match(req).then((cached) => cached || caches.match('./index.html'))
        )
    );
    return;
  }

  // CSS/JS: сеть в приоритете (чтобы обновления UI не залипали в кэше)
  if (/\.(?:css|js)$/i.test(url.pathname)) {
    event.respondWith(
      fetch(req)
        .then((res) => {
          if (res && res.status === 200) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(req, copy));
          }
          return res;
        })
        .catch(() => caches.match(req))
    );
    return;
  }

  // Картинки/шрифты: кэш → сеть
  event.respondWith(
    caches.match(req).then((cached) => {
      if (cached) return cached;
      return fetch(req).then((res) => {
        if (!res || res.status !== 200 || res.type === 'opaque') return res;
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(req, copy));
        return res;
      });
    })
  );
});
