/* Тодо Бичик — service worker (офлайн-кэш). */
const CACHE = 'todo-bichig-v63';

const PRECACHE = [
  './',
  './index.html',
  './writer.html',
  './manifest.webmanifest',
  './css/fonts.css',
  './css/style.css',
  './fonts/ibm-plex-sans/faces.css',
  './fonts/ibm-plex-sans/cyrillic-400-normal.woff2',
  './fonts/ibm-plex-sans/cyrillic-500-normal.woff2',
  './fonts/ibm-plex-sans/cyrillic-600-normal.woff2',
  './fonts/ibm-plex-sans/cyrillic-700-normal.woff2',
  './fonts/ibm-plex-sans/cyrillic-ext-400-normal.woff2',
  './fonts/ibm-plex-sans/cyrillic-ext-500-normal.woff2',
  './fonts/ibm-plex-sans/cyrillic-ext-600-normal.woff2',
  './fonts/ibm-plex-sans/cyrillic-ext-700-normal.woff2',
  './fonts/ibm-plex-sans/latin-400-normal.woff2',
  './fonts/ibm-plex-sans/latin-500-normal.woff2',
  './fonts/ibm-plex-sans/latin-600-normal.woff2',
  './fonts/ibm-plex-sans/latin-700-normal.woff2',
  './fonts/ibm-plex-sans/latin-ext-400-normal.woff2',
  './fonts/ibm-plex-sans/latin-ext-500-normal.woff2',
  './fonts/ibm-plex-sans/latin-ext-600-normal.woff2',
  './fonts/ibm-plex-sans/latin-ext-700-normal.woff2',
  './js/font-data.js',
  './js/barintodo-data.js',
  './js/data.js',
  './js/harmony-data.js',
  './js/reading-data.js',
  './js/utils.js',
  './js/audio.js',
  './js/lessons.js',
  './audio/vowels/a.m4a',
  './audio/vowels/e.m4a',
  './audio/vowels/i.m4a',
  './audio/vowels/o.m4a',
  './audio/vowels/u.m4a',
  './audio/vowels/oe.m4a',
  './audio/vowels/ue.m4a',
  './audio/long_vowels/aa.m4a',
  './audio/long_vowels/ee.m4a',
  './audio/long_vowels/ii.m4a',
  './audio/long_vowels/oo.m4a',
  './audio/long_vowels/uu.m4a',
  './audio/long_vowels/oee.m4a',
  './audio/long_vowels/oeu.m4a',
  './audio/diphthongs/ayi.m4a',
  './audio/diphthongs/eyi.m4a',
  './audio/diphthongs/iyi.m4a',
  './audio/diphthongs/oyi.m4a',
  './audio/diphthongs/uyi.m4a',
  './audio/diphthongs/oeyi.m4a',
  './audio/diphthongs/ueyi.m4a',
  './audio/consonants/n.m4a',
  './audio/consonants/ng.m4a',
  './audio/consonants/x.m4a',
  './audio/consonants/gh.m4a',
  './audio/consonants/b1.m4a',
  './audio/consonants/b2.m4a',
  './audio/consonants/s.m4a',
  './audio/consonants/sh.m4a',
  './audio/consonants/t.m4a',
  './audio/consonants/d.m4a',
  './audio/consonants/l.m4a',
  './audio/consonants/m.m4a',
  './audio/consonants/c.m4a',
  './audio/consonants/z.m4a',
  './audio/consonants/y.m4a',
  './audio/consonants/k1.m4a',
  './audio/consonants/k1n.m4a',
  './audio/consonants/k2.m4a',
  './audio/consonants/k2n.m4a',
  './audio/consonants/g1.m4a',
  './audio/consonants/g1n.m4a',
  './audio/consonants/q.m4a',
  './audio/consonants/r.m4a',
  './audio/consonants/v.m4a',
  './audio/galik/pb1.m4a',
  './audio/galik/pb2.m4a',
  './audio/galik/pf1.m4a',
  './audio/galik/pf2.m4a',
  './audio/galik/ch.m4a',
  './audio/galik/z1.m4a',
  './audio/galik/z2.m4a',
  './audio/galik/z3.m4a',
  './audio/galik/j.m4a',
  './audio/galik/xh.m4a',
  './audio/elements/nurhun.m4a',
  './audio/elements/udan.m4a',
  './audio/elements/titm.m4a',
  './audio/elements/aran.m4a',
  './audio/elements/neg_ceq.m4a',
  './audio/elements/xoyor_ceq.m4a',
  './audio/elements/togrg_ceq.m4a',
  './audio/elements/uru_tatasn.m4a',
  './audio/elements/kuchlg.m4a',
  './audio/numbers/0.m4a',
  './audio/numbers/1.m4a',
  './audio/numbers/2.m4a',
  './audio/numbers/3.m4a',
  './audio/numbers/4.m4a',
  './audio/numbers/5.m4a',
  './audio/numbers/6.m4a',
  './audio/numbers/7.m4a',
  './audio/numbers/8.m4a',
  './audio/numbers/9.m4a',
  './audio/punctuation/birga.m4a',
  './audio/punctuation/point4.m4a',
  './audio/punctuation/comma.m4a',
  './audio/punctuation/colon.m4a',
  './audio/words/w01.m4a',
  './audio/words/w02.m4a',
  './audio/words/w03.m4a',
  './audio/words/w04.m4a',
  './audio/words/w05.m4a',
  './audio/words/w06.m4a',
  './audio/words/w07.m4a',
  './audio/words/w08.m4a',
  './audio/words/w09.m4a',
  './audio/words/w10.m4a',
  './audio/words/w11.m4a',
  './audio/words/w12.m4a',
  './audio/words/w13.m4a',
  './audio/words/w14.m4a',
  './audio/words/w15.m4a',
  './audio/words/w16.m4a',
  './audio/words/w17.m4a',
  './audio/words/w18.m4a',
  './audio/words/w19.m4a',
  './audio/words/w20.m4a',
  './audio/words/w21.m4a',
  './audio/words/w22.m4a',
  './audio/words/w23.m4a',
  './audio/words/w24.m4a',
  './audio/words/w25.m4a',
  './audio/words/w26.m4a',
  './audio/words/w27.m4a',
  './audio/words/w28.m4a',
  './audio/words/w29.m4a',
  './audio/reading/expr/e01.m4a',
  './audio/reading/expr/e02.m4a',
  './audio/reading/expr/e03.m4a',
  './audio/reading/expr/e04.m4a',
  './audio/reading/expr/e05.m4a',
  './audio/reading/expr/e06.m4a',
  './audio/reading/expr/e07.m4a',
  './audio/reading/expr/e08.m4a',
  './audio/reading/expr/e09.m4a',
  './audio/reading/expr/e10.m4a',
  './audio/reading/expr/e11.m4a',
  './audio/reading/expr/e12.m4a',
  './audio/reading/expr/e13.m4a',
  './audio/reading/expr/e14.m4a',
  './audio/reading/expr/e15.m4a',
  './audio/reading/expr/e16.m4a',
  './audio/reading/expr/e17.m4a',
  './audio/reading/expr/e18.m4a',
  './audio/reading/expr/e19.m4a',
  './audio/reading/expr/e20.m4a',
  './audio/reading/expr/e21.m4a',
  './audio/reading/expr/e22.m4a',
  './audio/reading/riddles/r01q.m4a',
  './audio/reading/riddles/r01a.m4a',
  './audio/reading/riddles/r02q.m4a',
  './audio/reading/riddles/r02a.m4a',
  './audio/reading/riddles/r03q.m4a',
  './audio/reading/riddles/r03a.m4a',
  './audio/reading/riddles/r04q.m4a',
  './audio/reading/riddles/r04a.m4a',
  './audio/reading/riddles/r05q.m4a',
  './audio/reading/riddles/r05a.m4a',
  './audio/reading/riddles/r06q.m4a',
  './audio/reading/riddles/r06a.m4a',
  './audio/reading/riddles/r07q.m4a',
  './audio/reading/riddles/r07a.m4a',
  './audio/reading/riddles/r08q.m4a',
  './audio/reading/riddles/r08a.m4a',
  './audio/reading/riddles/r09q.m4a',
  './audio/reading/riddles/r09a.m4a',
  './audio/compose/c01.m4a',
  './audio/compose/c02.m4a',
  './audio/compose/c03.m4a',
  './audio/compose/c04.m4a',
  './audio/compose/c05.m4a',
  './audio/compose/c06.m4a',
  './audio/compose/c07.m4a',
  './audio/compose/c08.m4a',
  './audio/compose/c09.m4a',
  './audio/compose/c10.m4a',
  './audio/compose/c11.m4a',
  './audio/compose/c12.m4a',
  './audio/compose/c13.m4a',
  './audio/compose/c14.m4a',
  './audio/compose/c15.m4a',
  './audio/compose/c16.m4a',
  './audio/compose/c17.m4a',
  './audio/compose/c18.m4a',
  './audio/compose/c19.m4a',
  './audio/compose/c20.m4a',
  './audio/compose/c21.m4a',
  './audio/compose/c22.m4a',
  './audio/compose/c23.m4a',
  './audio/compose/c24.m4a',
  './audio/compose/c25.m4a',
  './audio/compose/c26.m4a',
  './audio/compose/c27.m4a',
  './audio/compose/c28.m4a',
  './audio/compose/c29.m4a',
  './audio/compose/c30.m4a',
  './audio/compose/c31.m4a',
  './audio/compose/c32.m4a',
  './audio/compose/c33.m4a',
  './audio/compose/c34.m4a',
  './audio/compose/c35.m4a',
  './audio/compose/c36.m4a',
  './audio/compose/c37.m4a',
  './audio/compose/c38.m4a',
  './audio/compose/c39.m4a',
  './audio/compose/c40.m4a',
  './audio/compose/c41.m4a',
  './audio/compose/c42.m4a',
  './audio/compose/c43.m4a',
  './audio/compose/c44.m4a',
  './audio/compose/c45.m4a',
  './audio/compose/c46.m4a',
  './audio/compose/c47.m4a',
  './audio/compose/c48.m4a',
  './audio/compose/c49.m4a',
  './audio/compose/c50.m4a',
  './audio/compose/c51.m4a',
  './audio/compose/c52.m4a',
  './audio/compose/c53.m4a',
  './audio/compose/c54.m4a',
  './audio/syllables/na.m4a',
  './audio/syllables/ne.m4a',
  './audio/syllables/ni.m4a',
  './audio/syllables/no.m4a',
  './audio/syllables/nu.m4a',
  './audio/syllables/noe.m4a',
  './audio/syllables/nue.m4a',
  './audio/syllables/ang.m4a',
  './audio/syllables/eng.m4a',
  './audio/syllables/ing.m4a',
  './audio/syllables/ong.m4a',
  './audio/syllables/ung.m4a',
  './audio/syllables/oeng.m4a',
  './audio/syllables/ueng.m4a',
  './audio/syllables/noeng.m4a',
  './audio/syllables/nueng.m4a',
  './audio/syllables/xa.m4a',
  './audio/syllables/xo.m4a',
  './audio/syllables/xu.m4a',
  './audio/syllables/gha.m4a',
  './audio/syllables/gho.m4a',
  './audio/syllables/ghu.m4a',
  './audio/syllables/ba.m4a',
  './audio/syllables/be.m4a',
  './audio/syllables/bi.m4a',
  './audio/syllables/bo.m4a',
  './audio/syllables/bu.m4a',
  './audio/syllables/boe.m4a',
  './audio/syllables/bue.m4a',
  './audio/syllables/pa.m4a',
  './audio/syllables/pe.m4a',
  './audio/syllables/pi.m4a',
  './audio/syllables/po.m4a',
  './audio/syllables/pu.m4a',
  './audio/syllables/poe.m4a',
  './audio/syllables/pue.m4a',
  './audio/syllables/fa.m4a',
  './audio/syllables/fe.m4a',
  './audio/syllables/fi.m4a',
  './audio/syllables/fo.m4a',
  './audio/syllables/fu.m4a',
  './audio/syllables/foe.m4a',
  './audio/syllables/fue.m4a',
  './audio/syllables/sa.m4a',
  './audio/syllables/se.m4a',
  './audio/syllables/si.m4a',
  './audio/syllables/so.m4a',
  './audio/syllables/su.m4a',
  './audio/syllables/soe.m4a',
  './audio/syllables/sue.m4a',
  './audio/syllables/sha.m4a',
  './audio/syllables/she.m4a',
  './audio/syllables/shi.m4a',
  './audio/syllables/sho.m4a',
  './audio/syllables/shu.m4a',
  './audio/syllables/shoe.m4a',
  './audio/syllables/shue.m4a',
  './audio/syllables/ta.m4a',
  './audio/syllables/te.m4a',
  './audio/syllables/ti.m4a',
  './audio/syllables/to.m4a',
  './audio/syllables/tu.m4a',
  './audio/syllables/toe.m4a',
  './audio/syllables/tue.m4a',
  './audio/syllables/da.m4a',
  './audio/syllables/de.m4a',
  './audio/syllables/di.m4a',
  './audio/syllables/do.m4a',
  './audio/syllables/du.m4a',
  './audio/syllables/doe.m4a',
  './audio/syllables/due.m4a',
  './audio/syllables/la.m4a',
  './audio/syllables/le.m4a',
  './audio/syllables/li.m4a',
  './audio/syllables/lo.m4a',
  './audio/syllables/lu.m4a',
  './audio/syllables/loe.m4a',
  './audio/syllables/lue.m4a',
  './audio/syllables/ma.m4a',
  './audio/syllables/me.m4a',
  './audio/syllables/mi.m4a',
  './audio/syllables/mo.m4a',
  './audio/syllables/mu.m4a',
  './audio/syllables/moe.m4a',
  './audio/syllables/mue.m4a',
  './audio/syllables/ca.m4a',
  './audio/syllables/ce.m4a',
  './audio/syllables/chi.m4a',
  './audio/syllables/co.m4a',
  './audio/syllables/cu.m4a',
  './audio/syllables/coe.m4a',
  './audio/syllables/cue.m4a',
  './audio/syllables/za.m4a',
  './audio/syllables/ze.m4a',
  './audio/syllables/zi.m4a',
  './audio/syllables/zo.m4a',
  './audio/syllables/zu.m4a',
  './audio/syllables/zoe.m4a',
  './audio/syllables/zue.m4a',
  './audio/syllables/ja.m4a',
  './audio/syllables/je.m4a',
  './audio/syllables/ji.m4a',
  './audio/syllables/jo.m4a',
  './audio/syllables/ju.m4a',
  './audio/syllables/joe.m4a',
  './audio/syllables/jue.m4a',
  './audio/syllables/ya.m4a',
  './audio/syllables/ye.m4a',
  './audio/syllables/yi.m4a',
  './audio/syllables/yo.m4a',
  './audio/syllables/yu.m4a',
  './audio/syllables/yoe.m4a',
  './audio/syllables/yue.m4a',
  './audio/syllables/ka.m4a',
  './audio/syllables/ko.m4a',
  './audio/syllables/ku.m4a',
  './audio/syllables/ke.m4a',
  './audio/syllables/ki.m4a',
  './audio/syllables/koe.m4a',
  './audio/syllables/kue.m4a',
  './audio/syllables/ge.m4a',
  './audio/syllables/gi.m4a',
  './audio/syllables/goe.m4a',
  './audio/syllables/gue.m4a',
  './audio/syllables/ra.m4a',
  './audio/syllables/re.m4a',
  './audio/syllables/ri.m4a',
  './audio/syllables/ro.m4a',
  './audio/syllables/ru.m4a',
  './audio/syllables/roe.m4a',
  './audio/syllables/rue.m4a',
  './audio/syllables/va.m4a',
  './audio/syllables/ve.m4a',
  './audio/syllables/vi.m4a',
  './audio/syllables/vo.m4a',
  './audio/syllables/vu.m4a',
  './audio/syllables/voe.m4a',
  './audio/syllables/vue.m4a',
  './audio/syllables/ha.m4a',
  './audio/syllables/he.m4a',
  './audio/syllables/hi.m4a',
  './audio/syllables/ho.m4a',
  './audio/syllables/hu.m4a',
  './audio/syllables/hoe.m4a',
  './audio/syllables/hue.m4a',
  './js/ui.js',
  './js/search.js',
  './js/practice.js',
  './js/harmony.js',
  './js/path.js',
  './js/copybook.js',
  './js/writer.js',
  './js/main.js',
  './js/writer-data.js',
  './js/writer-strokes-saved.js',
  './js/vendor/jspdf.umd.min.js',
  './img/icons/logo-192.png',
  './img/icons/icon-192.png',
  './img/icons/icon-512.png',
  './img/icons/icon-512-maskable.png',
  './img/icons/apple-touch-icon.png',
  './img/zaya-pandita.webp',
  './img/zaya-pandita.jpg',
  './img/badmaev.jpg',
  './img/vowels-strokes.webp',
  './img/vowels-strokes.jpg',
  './img/consonants-strokes-1.webp',
  './img/consonants-strokes-1.jpg',
  './img/consonants-strokes-2.webp',
  './img/consonants-strokes-2.jpg',
  './img/copybook/1.webp',
  './img/copybook/2.webp',
  './img/copybook/3.webp'
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) =>
      cache.addAll(PRECACHE).catch((err) => {
        console.warn('[sw] precache partial fail', err);
        return Promise.all(
          PRECACHE.map((url) =>
            cache.add(url).catch((e) => console.warn('[sw] skip', url, e))
          )
        );
      })
    ).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;

  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // HTML: сеть в приоритете, офлайн — из кэша
  if (req.mode === 'navigate' || (req.headers.get('accept') || '').includes('text/html')) {
    event.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
          return res;
        })
        .catch(() =>
          caches.match(req).then((cached) => cached || caches.match('./index.html'))
        )
    );
    return;
  }

  // CSS/JS: сеть в приоритете (чтобы обновления UI не залипали в кэше)
  if (/\.(?:css|js)$/i.test(url.pathname)) {
    event.respondWith(
      fetch(req)
        .then((res) => {
          if (res && res.status === 200) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(req, copy));
          }
          return res;
        })
        .catch(() => caches.match(req))
    );
    return;
  }

  // Картинки/шрифты: кэш → сеть
  event.respondWith(
    caches.match(req).then((cached) => {
      if (cached) return cached;
      return fetch(req).then((res) => {
        if (!res || res.status !== 200 || res.type === 'opaque') return res;
        const copy = res.clone();
        caches.open(CACHE).then((c) => c.put(req, copy));
        return res;
      });
    })
  );
});
